import { z } from "zod"
import { translations, type Language } from "@/ai-form/lib/translations"

export const createMedicalFormSchema = (language: Language = "ru") => {
  const t = translations[language]

  const genderValues: string[] = [
    translations.ru.personalData.male,
    translations.ru.personalData.female,
    translations.uz.personalData.male,
    translations.uz.personalData.female,
    translations.en.personalData.male,
    translations.en.personalData.female,
  ]

  return z.object({
    fullName: z.string().min(2, t.validation.fullNameMin),
    passport: z.string().optional(),
    birthDate: z.string().optional(),
    gender: z.string().refine(
      (val): val is string => !val || val === "" || genderValues.includes(val),
      { message: t.validation.genderRequired }
    ).optional(),
    maritalStatus: z.string().optional(),
    education: z.string().optional(),
    job: z.string().optional(),
    address: z.string().optional(),
    nationality: z.string().optional(),
    profession: z.string().optional(),
    position: z.string().optional(),

    admissionDate: z.string().optional(),
    referralDiagnosis: z.string().optional(),
    mainComplaints: z.string().optional(),
    mainComplaintsDetail: z.string().optional(),
    generalComplaints: z.string().optional(),
    additionalComplaints: z.string().optional(),
    firstSymptomsDate: z.string().optional(),
    firstSymptoms: z.string().optional(),
    triggers: z.string().optional(),
    symptomsDynamic: z.string().optional(),
    previousDiagnosis: z.string().optional(),
    currentState: z.string().optional(),

    badHabits: z.string().optional(),
    familyHistory: z.string().optional(),
    allergies: z.string().optional(),
    pastDiseases: z.string().optional(),

    generalExamination: z.string().optional(),
    headNeck: z.string().optional(),
    skin: z.string().optional(),
    respiratory: z.string().optional(),
    cardiovascular: z.string().optional(),
    abdomen: z.string().optional(),
    musculoskeletal: z.string().optional(),
    lymphNodes: z.string().optional(),
    abdomenPalpation: z.string().optional(),
    percussion: z.string().optional(),
    lungAuscultation: z.string().optional(),
    heartAuscultation: z.string().optional(),
    abdomenAuscultation: z.string().optional(),

    oak_wbc: z.string().optional(),
    oak_rbc: z.string().optional(),
    oak_hgb: z.string().optional(),
    oak_hct: z.string().optional(),
    oak_mcv: z.string().optional(),
    oak_mch: z.string().optional(),
    oak_mchc: z.string().optional(),
    oak_rdw_cv: z.string().optional(),
    oak_rdw_sd: z.string().optional(),
    oak_plt: z.string().optional(),
    oak_pct: z.string().optional(),
    oak_mpv: z.string().optional(),
    oak_pdw: z.string().optional(),

    oam_color: z.string().optional(),
    oam_transparency: z.string().optional(),
    oam_sediment: z.string().optional(),
    oam_ph_reaction: z.string().optional(),
    oam_bilirubin: z.string().optional(),
    oam_urobilinogen: z.string().optional(),
    oam_ketones: z.string().optional(),
    oam_ascorbic_acid: z.string().optional(),
    oam_glucose: z.string().optional(),
    oam_protein: z.string().optional(),
    oam_blood: z.string().optional(),
    oam_ph: z.string().optional(),
    oam_nitrites: z.string().optional(),
    oam_leukocytes_digital: z.string().optional(),
    oam_specific_gravity: z.string().optional(),
    oam_epithelium: z.string().optional(),
    oam_leukocytes_microscopy: z.string().optional(),
    oam_erythrocytes_unchanged: z.string().optional(),
    oam_erythrocytes_changed: z.string().optional(),
    oam_bacteria: z.string().optional(),
    oam_mucus: z.string().optional(),

    bio_bilt: z.string().optional(),
    bio_bild: z.string().optional(),
    bio_ast: z.string().optional(),
    bio_alt: z.string().optional(),
    bio_urea: z.string().optional(),
    bio_crea: z.string().optional(),
    bio_tp: z.string().optional(),
    bio_alb: z.string().optional(),
    bio_alp: z.string().optional(),
    bio_amy: z.string().optional(),
    bio_glue: z.string().optional(),
    bio_ldh: z.string().optional(),
    bio_glob: z.string().optional(),
    bio_alb_glob: z.string().optional(),
    bio_ritis: z.string().optional(),

    imm_cd3: z.string().optional(),
    imm_cd3_hla_dr: z.string().optional(),
    imm_cd4_cd8_minus: z.string().optional(),
    imm_cd4_minus_cd8: z.string().optional(),
    imm_cd4_cd8_ratio: z.string().optional(),
    imm_cd3_minus_cd8: z.string().optional(),
    imm_cd4_minus_cd8_alt: z.string().optional(),
    imm_cd19: z.string().optional(),
    imm_cd16_cd56: z.string().optional(),
    imm_cd3_cd16_cd56: z.string().optional(),
    imm_cd3_cd25: z.string().optional(),
    imm_cd8_hla_dr: z.string().optional(),
    imm_cd19_cd27_igd: z.string().optional(),
    imm_leukocytes: z.string().optional(),
    imm_lymphocytes_percent: z.string().optional(),
    imm_igg: z.string().optional(),
    imm_igm: z.string().optional(),
    imm_iga: z.string().optional(),

    sero_early_igg: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_early_igm: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_acute_igg: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_acute_igm: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_immunity_igg: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_immunity_igm: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_risk_igg: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),
    sero_risk_igm: z.string().refine((val) => !val || val === "+" || val === "-", { message: t.validation.selectPlusOrMinus }).optional(),

    pcr_chlamydia: z.string().optional(),
    pcr_ureaplasma: z.string().optional(),
    pcr_mycoplasma_hominis: z.string().optional(),
    pcr_mycoplasma_genitalium: z.string().optional(),
    pcr_herpes: z.string().optional(),
    pcr_cmv: z.string().optional(),
    pcr_gonorrhea: z.string().optional(),
    pcr_trichomonas: z.string().optional(),
    pcr_gardnerella: z.string().optional(),
    pcr_candida: z.string().optional(),
    pcr_hpv_high: z.string().optional(),
    pcr_hpv_low: z.string().optional(),
    pcr_streptococcus: z.string().optional(),

    oak_conclusion: z.string().optional(),
    oam_conclusion: z.string().optional(),
    bio_conclusion: z.string().optional(),
    imm_conclusion: z.string().optional(),
    sero_conclusion: z.string().optional(),
    pcr_conclusion: z.string().optional(),

    instrumental_research: z.array(
      z.object({
        id: z.string().optional(),
        type: z.string().min(1, t.validation.typeRequired || "Тип исследования обязателен"),
        date: z.string().optional(),
        performingDoctor: z.string().optional(),
        institution: z.string().optional(),
        images: z.array(z.string()).optional(),
        imageAnalyses: z.array(z.string()).optional(), // AI tahlil natijalari
        comment: z.string().optional(),
      })
    ).optional(),
  })
}

export const medicalFormSchema = createMedicalFormSchema("ru")
export type MedicalFormData = z.infer<ReturnType<typeof createMedicalFormSchema>>


